[platformio]
src_dir = src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ${platformio.packages_dir}/framework-arduinoespressif32/libraries
lib_deps =
  2029
  bblanchon/ArduinoJson@^7.4.2
  knolleary/PubSubClient@^2.8

[env:wokwi]
extends = env:esp32dev
build_flags = -DWOKWI_SIMULATION
