IF DB_ID(N'ColdChainDB') IS NULL CREATE DATABASE ColdChainDB;
GO
USE ColdChainDB;
GO
IF OBJECT_ID('dbo.vehicles','U') IS NULL CREATE TABLE vehicles (vehicle_id INT IDENTITY(1,1) PRIMARY KEY, license_plate VARCHAR(20) NOT NULL UNIQUE, vehicle_name NVARCHAR(100), vehicle_type NVARCHAR(50), status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE', created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.products','U') IS NULL CREATE TABLE products (product_id VARCHAR(30) PRIMARY KEY, product_name NVARCHAR(150) NOT NULL, description NVARCHAR(500));
IF OBJECT_ID('dbo.storage_profiles','U') IS NULL CREATE TABLE storage_profiles (profile_id VARCHAR(50) PRIMARY KEY, profile_name NVARCHAR(150) NOT NULL, min_temperature FLOAT NULL, max_temperature FLOAT NULL, early_warning_minutes INT NOT NULL DEFAULT 10, max_door_open_seconds INT NOT NULL DEFAULT 30, description NVARCHAR(500), CONSTRAINT CK_profile_temp CHECK (min_temperature IS NULL OR max_temperature IS NULL OR min_temperature <= max_temperature));
IF OBJECT_ID('dbo.lots','U') IS NULL CREATE TABLE lots (lot_id VARCHAR(50) PRIMARY KEY, product_id VARCHAR(30) NOT NULL REFERENCES products(product_id), profile_id VARCHAR(50) REFERENCES storage_profiles(profile_id), quantity INT NULL CHECK (quantity IS NULL OR quantity > 0), qr_code VARCHAR(255) UNIQUE, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.trips','U') IS NULL CREATE TABLE trips (trip_id VARCHAR(30) PRIMARY KEY, vehicle_id INT NOT NULL REFERENCES vehicles(vehicle_id), profile_id VARCHAR(50) NOT NULL REFERENCES storage_profiles(profile_id), min_temperature FLOAT NULL, max_temperature FLOAT NULL, early_warning_minutes INT NOT NULL DEFAULT 10, max_door_open_seconds INT NOT NULL DEFAULT 30, trip_state VARCHAR(20) NOT NULL DEFAULT 'IDLE' CHECK (trip_state IN ('IDLE','ARMED','IN_TRANSIT','COMPLETED')), delivery_mode BIT NOT NULL DEFAULT 0, start_time DATETIMEOFFSET NULL, end_time DATETIMEOFFSET NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT CK_trip_temperature CHECK (min_temperature IS NULL OR max_temperature IS NULL OR min_temperature <= max_temperature));
IF OBJECT_ID('dbo.trip_lots','U') IS NULL CREATE TABLE trip_lots (trip_id VARCHAR(30) NOT NULL REFERENCES trips(trip_id), lot_id VARCHAR(50) NOT NULL REFERENCES lots(lot_id), assigned_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), PRIMARY KEY(trip_id, lot_id));
IF OBJECT_ID('dbo.devices','U') IS NULL CREATE TABLE devices (device_id VARCHAR(50) PRIMARY KEY, vehicle_id INT NULL REFERENCES vehicles(vehicle_id), device_name NVARCHAR(100), status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE' CHECK(status IN ('ONLINE','OFFLINE')), last_seen DATETIMEOFFSET NULL, created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
IF OBJECT_ID('dbo.sensors','U') IS NULL CREATE TABLE sensors (device_id VARCHAR(50) NOT NULL REFERENCES devices(device_id), sensor_id VARCHAR(20) NOT NULL, zone_name NVARCHAR(100), sensor_type VARCHAR(30) NOT NULL DEFAULT 'DHT22', status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE' CHECK(status IN ('ONLINE','OFFLINE','FAULT')), last_seen DATETIMEOFFSET NULL, PRIMARY KEY(device_id,sensor_id));
IF OBJECT_ID('dbo.telemetry_packets','U') IS NULL CREATE TABLE telemetry_packets (packet_id BIGINT IDENTITY(1,1) PRIMARY KEY, device_id VARCHAR(50) NOT NULL REFERENCES devices(device_id), trip_id VARCHAR(30) NOT NULL REFERENCES trips(trip_id), message_id NVARCHAR(100) NULL, door_status VARCHAR(10) CHECK(door_status IN ('OPEN','CLOSED')), latitude FLOAT CHECK(latitude IS NULL OR latitude BETWEEN -90 AND 90), longitude FLOAT CHECK(longitude IS NULL OR longitude BETWEEN -180 AND 180), measured_at DATETIMEOFFSET NOT NULL, received_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), is_buffered BIT NOT NULL DEFAULT 0, message_type VARCHAR(20) NOT NULL DEFAULT 'TELEMETRY', CONSTRAINT UQ_packet_device UNIQUE(packet_id,device_id));
IF OBJECT_ID('dbo.sensor_readings','U') IS NULL CREATE TABLE sensor_readings (reading_id BIGINT IDENTITY(1,1) PRIMARY KEY, packet_id BIGINT NOT NULL, device_id VARCHAR(50) NOT NULL, sensor_id VARCHAR(20) NOT NULL, temperature FLOAT NULL, humidity FLOAT NULL CHECK(humidity IS NULL OR humidity BETWEEN 0 AND 100), sensor_status VARCHAR(20) NOT NULL CHECK(sensor_status IN ('ONLINE','OFFLINE','FAULT')), FOREIGN KEY(packet_id,device_id) REFERENCES telemetry_packets(packet_id,device_id), FOREIGN KEY(device_id,sensor_id) REFERENCES sensors(device_id,sensor_id), CONSTRAINT UQ_packet_sensor UNIQUE(packet_id,sensor_id));
IF OBJECT_ID('dbo.alerts','U') IS NULL CREATE TABLE alerts (alert_id BIGINT IDENTITY(1,1) PRIMARY KEY, trip_id VARCHAR(30) NOT NULL REFERENCES trips(trip_id), device_id VARCHAR(50) NULL REFERENCES devices(device_id), sensor_id VARCHAR(20) NULL, packet_id BIGINT NULL REFERENCES telemetry_packets(packet_id), alert_type VARCHAR(50) NOT NULL, temperature FLOAT NULL, threshold_value FLOAT NULL, message NVARCHAR(500), created_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), last_seen_at DATETIMEOFFSET NOT NULL CONSTRAINT DF_alerts_last_seen_at DEFAULT SYSDATETIMEOFFSET(), occurrence_count INT NOT NULL CONSTRAINT DF_alerts_occurrence_count DEFAULT 1, status VARCHAR(20) NOT NULL CONSTRAINT DF_alerts_status DEFAULT 'OPEN', resolved_at DATETIMEOFFSET NULL, recovered_at DATETIMEOFFSET NULL, FOREIGN KEY(device_id,sensor_id) REFERENCES sensors(device_id,sensor_id), CONSTRAINT CK_alerts_status CHECK (status IN ('OPEN','RESOLVED')));
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_telemetry_trip_time') CREATE INDEX IX_telemetry_trip_time ON telemetry_packets(trip_id, measured_at);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_telemetry_device_time') CREATE INDEX IX_telemetry_device_time ON telemetry_packets(device_id, measured_at);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_readings_sensor_time') CREATE INDEX IX_readings_sensor_time ON sensor_readings(device_id, sensor_id, packet_id);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_alerts_trip_time') CREATE INDEX IX_alerts_trip_time ON alerts(trip_id, created_at);
IF COL_LENGTH('dbo.telemetry_packets','message_id') IS NULL ALTER TABLE dbo.telemetry_packets ADD message_id NVARCHAR(100) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='UX_telemetry_device_message_id' AND object_id=OBJECT_ID('dbo.telemetry_packets')) CREATE UNIQUE INDEX UX_telemetry_device_message_id ON dbo.telemetry_packets(device_id,message_id) WHERE message_id IS NOT NULL;
IF COL_LENGTH('storage_profiles','early_warning_minutes') IS NULL ALTER TABLE storage_profiles ADD early_warning_minutes INT NOT NULL CONSTRAINT DF_storage_profiles_warning DEFAULT 10;
IF COL_LENGTH('storage_profiles','max_door_open_seconds') IS NULL ALTER TABLE storage_profiles ADD max_door_open_seconds INT NOT NULL CONSTRAINT DF_storage_profiles_door DEFAULT 30;
GO
IF COL_LENGTH('dbo.alerts','status') IS NULL ALTER TABLE dbo.alerts ADD status VARCHAR(20) NOT NULL CONSTRAINT DF_alerts_status DEFAULT 'OPEN';
IF COL_LENGTH('dbo.alerts','resolved_at') IS NULL ALTER TABLE dbo.alerts ADD resolved_at DATETIMEOFFSET NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_alerts_status' AND parent_object_id = OBJECT_ID('dbo.alerts')) ALTER TABLE dbo.alerts ADD CONSTRAINT CK_alerts_status CHECK (status IN ('OPEN','RESOLVED'));
GO
